name: PR Build Check

on:
  pull_request:
    branches: [main]
    paths:
      - "*.nix"
      - ".github/workflows/pr.yml"

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            max-jobs = auto
            cores = 0

      - name: Build ISO
        run: nix build .#iso --print-build-logs

      - name: Prepare artifact
        run: |
          mkdir -p out
          find result/ -type f -name '*.iso' -exec cp {} out/ \;

      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollamalive-iso-pr${{ github.event.pull_request.number }}
          path: out/
          compression-level: 0
          retention-days: 14
